Update Controller/Component/OAuthComponent.php
It breaks in linux because of the lib lowercase name in the App:import
Fatal error: Class 'OAuth2' not found in /var/www/yourapp.com/app/Plugin/OAuth/Controller/Component/OAuthComponent.php on line 144